[deps]
Atom = "c52e3926-4ff0-5f6e-af25-54175e0327b1"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OptimPack = "04a3d532-ba69-5937-989a-472689bdb720"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SoftGlobalScope = "b85f4697-e234-5449-a836-ec8e2f98b302"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
